version: 2.1 # CircleCI 버전

jobs:
  build_and_push:
    docker: # Docker 실행
      - image: cimg/node:20.3.1 # Node.js 이미지 사용
    steps: # 실행할 명령어
      - checkout
      # CircleCI 프로젝트 기본 코드를 가져옴
      # 기본적으로 해당 레파지토리의 .circleci/config.yml 파일을 가져오는데 전부 가져오고 싶다면 checkout을 사용해야 함
      # .circleci/config.yml 이외의 파일들이 docker 빌드할 때 사용하기 때문에 가져와야함
      - setup_remote_docker
      # Docker 레지스트리에 접근하기 위한 설정
      # docker나 docker-compose 명령어를 사용하기 위해서 반드시 써야 함
      - run: # Docker 이미지 빌드 및 푸시
          name: Lets build and push image
          command: |
            version="build-$CIRCLE_BUILD_NUM"
            echo $version
            docker build -t swordbill/todo-app:$version .
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            docker push swordbill/todo-app:$version
          # 버전을 CIRCLE_BUILD_NUM (circleci 빌드 실행시 자동으로 결정됨) 환경변수로 설정
          # Docker 이미지 빌드, 로그인, 푸시

  Update_menifest: # Menifest 파일 업데이트
    docker: # Docker 실행
      - image: cimg/base:2023.06 # circleci 우분투 기본 이미지 사용
    steps:
      - run:
          name: Updating Menifest file
          command: |
            TAG=$CIRCLE_BUILD_NUM
            ((TAG--))
            git clone https://github.com/swordbillz/kube_manifest-4thWeekOfCloudOps.git
            git config --global user.email "swordbillz@gmail.com" 
            git config --global user.name "swordbillz"
            cd kube_manifest-4thWeekOfCloudOps
            sed -i "s/build-[0-9]\{1,\}/build-$TAG/g" menifest/deployment.yaml
            git add .
            git commit -m "new build with imgTag build-$TAG"
            git config credential.helper 'cache --timeout=120'
            git push -q https://$GITHUB_PERSONAL_TOKEN@github.com/swordbillz/kube_manifest-4thWeekOfCloudOps.git main
          # TAG 환경변수에 CIRCLE_BUILD_NUM을 사용 (CIRCLE_BUILD_NUM은 jobs 하나당 1씩 올라감)
          # TAG를 1 감소시킴. build_and_push 단계에서 docker 이미지 빌드했을 때 사용한 태그를 똑같이 사용하기 위해 1을 감소시킴
          # Github kube_manifest-4thWeekOfCloudOps 레파지토리 클론
          # deployment.yaml 파일에서 build-로 시작하는 부분을 build-$TAG로 변경
          # 변경된 파일을 git에 추가, 커밋
          # 120초간 인증 절차를 요구하지 않도록 설정 (clone, pull, push 등 저장소에 대해서 특정 작업을 하려고 할 때마다 유저 이름과 비밀번호를 요구하는걸 방지하기 위함)
          # Github 개인 액세스 토큰을 사용하여 push (-q 옵션은 quiet 설정, 로그를 출력하지 않음)
          # -> Kubernetes에서 업데이트된 manifest 파일을 사용하여 배포를 진행, 자동으로 최신 이미지를 끌어다가 사용함
workflows: # 워크플로우 설정
  GitOpsflow: # 워크플로우 이름
    jobs:
      - build_and_push # build_and_push 작업 실행
      - Update_menifest: # Update_menifest 작업 실행
          requires: # Update_menifest 작업은 build_and_push 작업이 성공적으로 완료되어야 함
            - build_and_push
